---
title: "Figures"
author: "Vyas Koduvayur"
date: "2025-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(reshape2)
library(readxl)
library(GGally)
library(RColorBrewer)
library(dplyr)
library(car)
library(ggridges)


```

```{r}
# FIGURE 1

# Load the data from the Excel file
data <- read_excel("../intermediate_data/LR_ANOVA_ATC_Level234.xlsx")

# Reshape the data for easier plotting
melted_data <- melt(data, id.vars = "Side Effect", 
                    measure.vars = c("LR: ATC Level 2", "LR: ATC Level 3", "LR: ATC Level 4", "LR: ATC Level 5"),
                    variable.name = "ATC Level", value.name = "LR")

# Modify the ATC Level names for labeling
melted_data$`ATC Level` <- factor(melted_data$`ATC Level`,
                                  levels = c("LR: ATC Level 2", "LR: ATC Level 3", "LR: ATC Level 4", "LR: ATC Level 5"),
                                  labels = c("Level 2", "Level 3", "Level 4", "Level 5"))

# Color Palette
colors <- c("Level 2" = "#FF6347", "Level 3" = "#4682B4", 
            "Level 4" = "#FF4500", "Level 5" = "#1E90FF")

# Create the plot
ggplot(melted_data, aes(x = `ATC Level`, y = LR)) +
  # Violin plot
  geom_violin(aes(fill = `ATC Level`), alpha = 0.6, show.legend = FALSE) +
  # Jittered points
  geom_jitter(aes(color = `ATC Level`), width = 0.1, size = 3, alpha = 0.5) +
  # Customize colors
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  # Plot appearance tuning
  theme_minimal(base_size = 14) +
  labs(title = "LR Model Performance Across ATC Code Levels",
       x = "ATC Code Level",
       y = "Model Accuracy") +
  theme(
    plot.title = element_text(size = 15, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    panel.grid.major = element_line(color = "gray", linetype = "dashed", size = 0.5)
  )


```


```{r}
# FIGURE 2B


# Load the data from the Excel file 
data <- read_excel("../intermediate_data/LR_ANOVA_ATC_Level234.xlsx")

# Select the relevant columns for correlation matrix
corr_data <- data[, c('LR: ATC Level 2', 'LR: ATC Level 3', 'LR: ATC Level 4', 'LR: ATC Level 5')]

# Calculate the correlation matrix
corr_matrix <- cor(corr_data)

# Melt the correlation matrix
corr_matrix_melted <- melt(corr_matrix)

blue_palette <- brewer.pal(9, "Blues") 

# Create the heatmap 
ggplot(corr_matrix_melted, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradientn(colors = blue_palette, limits = c(-1, 1), name = "Correlation") +
  geom_text(aes(label = round(value, 2)), color = "white", size = 2.5, fontface = "bold") +  
  theme_minimal(base_size = 14) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 12, face = "bold"),
    panel.grid = element_blank(),
    plot.margin = margin(10, 10, 10, 10)
  ) +
  labs(
    title = "Correlation Heatmap Across ATC Levels",
    x = "ATC Levels",
    y = "ATC Levels"
  ) +
  scale_x_discrete(labels = c("LR: ATC Level 2" = "Level 2", 
                              "LR: ATC Level 3" = "Level 3", 
                              "LR: ATC Level 4" = "Level 4", 
                              "LR: ATC Level 5" = "Level 5")) + 
  scale_y_discrete(labels = c("LR: ATC Level 2" = "Level 2", 
                              "LR: ATC Level 3" = "Level 3", 
                              "LR: ATC Level 4" = "Level 4", 
                              "LR: ATC Level 5" = "Level 5")) +  
  coord_fixed() 

```
```{r}
#Figure 3


# Load the Excel file
file_path <- '../intermediate_data/LR_ANOVA_ATC_Level234.xlsx'
data <- read_excel(file_path)

# Extract the data for Level 2 and Level 4
level_2 <- data$`LR: ATC Level 2`
level_4 <- data$`LR: ATC Level 4`
side_effects <- data$`Side Effect`

# Calculate mean differences
mean_differences <- level_4 - level_2

# Create a data frame with side effects and mean differences
results <- data.frame(
  Side_Effect = side_effects,
  Mean_Difference = mean_differences
)

# Sort by mean difference
results_sorted <- results %>% arrange(desc(Mean_Difference))

# Select the top 30 side effects
top_results <- head(results_sorted, 30)

# Create the plot using ggplot2
ggplot(top_results, aes(x = reorder(Side_Effect, Mean_Difference), y = Mean_Difference, fill = Mean_Difference)) +
  geom_bar(stat = 'identity', show.legend = FALSE) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  labs(
    title = "Top 30 Side Effects Sorted by Mean Difference",
    x = "Side Effect",
    y = "Mean Difference (Level 4 - Level 2)"
  ) +
  theme_minimal(base_size = 15) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 15, hjust = .3),
    axis.text.y = element_text(size = 8),  # Smaller y-axis text size

    axis.title = element_text(face = "bold", size = 12)
  ) +
  coord_flip()

```

```{r}
# FIGURE 4

# Perform Shapiro-Wilk test for normality for Level 2
shapiro_level_2 <- shapiro.test(level_2)

# Perform Shapiro-Wilk test for normality for Level 4
shapiro_level_4 <- shapiro.test(level_4)

# Print the results
shapiro_level_2
shapiro_level_4



# Perform Levene's test for equality of variances
levene_test <- leveneTest(c(level_2, level_4) ~ factor(c(rep(2, length(level_2)), rep(4, length(level_4)))))
levene_test

# Perform independent t-test to compare Level 2 and Level 4
t_test_result <- t.test(level_2, level_4)

# Print the t-test result
t_test_result

# Create a data frame for plotting
comparison_data <- data.frame(
  Value = c(level_2, level_4),
  Level = factor(c(rep("Level 2", length(level_2)), rep("Level 4", length(level_4))))
)

# Plot the boxplot
ggplot(comparison_data, aes(x = Level, y = Value, fill = Level)) +
  geom_boxplot() +
  scale_fill_manual(values = c("lightblue", "lightcoral")) +
  labs(
    title = "Direct Comparison of Level 2 v. Level 4",
    x = "ATC Code Level",
    y = "Model Performance"
  ) +
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
    axis.title = element_text(face = "bold", size = 12)
  )


```


```{r}
#Figure 5A and B


# Load the  Excel file
file_path <- '../intermediate_data/LR_ANOVA_Tar_ATC_2_4.xlsx'
data <- read_excel(file_path)

# Extract the data for Level 2 and Level 4
level_2 <- data$`LR: Drug Targets with ATC Level 2`
level_4 <- data$`LR: Drug Targets with ATC Level 4`
side_effects <- data$`Side Effect`

# Calculate mean differences
mean_differences <- level_4 - level_2

# Create a data frame with side effects and mean differences
results <- data.frame(
  Side_Effect = side_effects,
  Mean_Difference = mean_differences
)

# Sort by mean difference
results_sorted <- results %>% arrange(desc(Mean_Difference))

# Select the top 30 side effects
top_results <- head(results_sorted, 30)

ggplot(top_results, aes(x = reorder(Side_Effect, Mean_Difference), y = Mean_Difference, fill = Mean_Difference)) +
  geom_bar(stat = 'identity', show.legend = FALSE) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  labs(
    title = "Top 30 Side Effects Sorted by Mean Difference",
    x = "Side Effect",
    y = "Mean Difference (Level 4 - Level 2)"
  ) +
  theme_minimal(base_size = 15) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 15, hjust = .3),
    axis.text.y = element_text(size = 8),  # Smaller y-axis text size

    axis.title = element_text(face = "bold", size = 12)
  ) +
  coord_flip()

# Reload the Excel file
file_path <- '../intermediate_data/LR_ANOVA_Tar_ATC_2_4.xlsx'
data <- read_excel(file_path)

# Extract the data for Level 2 and Level 4
level_2 <- data$`LR: Drug Targets with ATC Level 2`
level_4 <- data$`LR: Drug Targets with ATC Level 4`
side_effects <- data$`Side Effect`

# Create a data frame for boxplot comparison
comparison_data <- data.frame(
  Value = c(level_2, level_4),
  Level = factor(c(rep("Level 2", length(level_2)), rep("Level 4", length(level_4))))
)

# Plot the boxplot
ggplot(comparison_data, aes(x = Level, y = Value, fill = Level)) +
  geom_boxplot() +
  scale_fill_manual(values = c("lightblue", "lightcoral")) +
  labs(
    title = "Comparison of Level 2 v. Level 4 with DT",
    x = "ATC Code Level",
    y = "Model Performance"
  ) +
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
    axis.title = element_text(face = "bold", size = 12)
  )

# Statistical Tests

# 1. Shapiro-Wilk Test for normality for Level 2 and Level 4
shapiro_level_2 <- shapiro.test(level_2)
shapiro_level_4 <- shapiro.test(level_4)

# 2. Levene's Test for equality of variances (center = median)
levene_test <- leveneTest(c(level_2, level_4) ~ factor(c(rep(2, length(level_2)), rep(4, length(level_4)))))

# 3. T-test to compare Level 2 and Level 4
t_test_result <- t.test(level_2, level_4)

# Print statistical test results
print(shapiro_level_2)
print(shapiro_level_4)
print(levene_test)
print(t_test_result)

```



```{r}


# Load the first Excel file
file_path_1 <- '../intermediate_data/LR_tar_approved.xlsx'
data_1 <- read_excel(file_path_1)
data_1 <- data_1[, 2:31]

# Load the second Excel file
file_path_2 <- '../intermediate_data/LR_tar_approved_tuned.xlsx'
data_2 <- read_excel(file_path_2)
data_2 <- data_2[, 2:31]

# Calculate the mean for each side effect (column) in data_1
mean_data_1 <- colMeans(data_1, na.rm = TRUE)

# Calculate the mean for each side effect (column) in data_2
mean_data_2 <- colMeans(data_2, na.rm = TRUE)

# Perform a t-test for the means of the untuned vs tuned
t_test_results <- t.test(mean_data_1, mean_data_2)
print(t_test_results)

# Create a data frame for the first file with side effects and their corresponding mean values
side_effects_1 <- colnames(data_1) 
mean_data_1_df <- data.frame(Side_Effect = side_effects_1, Mean_Value = mean_data_1)

# Create a data frame for the second file with side effects and their corresponding mean values
side_effects_2 <- colnames(data_2) 
mean_data_2_df <- data.frame(Side_Effect = side_effects_2, Mean_Value = mean_data_2)

# Calculate the mean differences between the two files
mean_differences <- mean_data_2 - mean_data_1

# Create a data frame with side effects and mean differences
results <- data.frame(
  Side_Effect = side_effects_1,  
  Mean_Difference = mean_differences
)

# Sort by mean difference
results_sorted <- results %>% arrange(desc(Mean_Difference))

# Select the top 30 side effects
top_results <- head(results_sorted, 30)

# Create the plot
ggplot(top_results, aes(x = reorder(Side_Effect, Mean_Difference), y = Mean_Difference, fill = Mean_Difference)) +
  geom_bar(stat = 'identity', show.legend = FALSE) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  labs(
    title = "Mean Difference of Top 30 Side Effects (Approved Drugs)",
    x = "Side Effect",
    y = "Mean Difference (Tuned - Untuned)"
  ) +
  theme_minimal(base_size = 15) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 13, hjust = .3),
    axis.text.y = element_text(size = 8),  # Smaller y-axis text size
    axis.title = element_text(face = "bold", size = 12)
  ) +
  coord_flip() 
```

```{r}

# Load the first  file
file_path_1 <- '../intermediate_data/LR_tar_approved.xlsx'
data_1 <- read_excel(file_path_1)[, 2:31]

# Load the second  file
file_path_2 <- '../intermediate_data/LR_tar_approved_tuned.xlsx'
data_2 <- read_excel(file_path_2)[, 2:31]

# Calculate the mean for each side effect 
mean_data_1 <- colMeans(data_1, na.rm = TRUE)
mean_data_2 <- colMeans(data_2, na.rm = TRUE)

# Create a dataframe with mean differences
results <- data.frame(
  Side_Effect = colnames(data_1),
  Mean_Difference = mean_data_2 - mean_data_1
)

# Select the top 10 side effects with the largest mean difference
top_results <- results %>% arrange(desc(Mean_Difference)) %>% head(10)

# Melt data for plotting
data_1_long <- melt(data_1)
data_2_long <- melt(data_2)

# Filter data to keep only the top 10 side effects
data_1_filtered <- data_1_long %>% filter(variable %in% top_results$Side_Effect)
data_2_filtered <- data_2_long %>% filter(variable %in% top_results$Side_Effect)

data_1_filtered$variable <- factor(data_1_filtered$variable, levels = rev(top_results$Side_Effect))
data_2_filtered$variable <- factor(data_2_filtered$variable, levels = rev(top_results$Side_Effect))

custom_colors <- c("Untuned" = "#537ec5", "Tuned" = "#d1495b")  # Deep blue & warm red

# Plot
ggplot() +
  geom_density_ridges(data = data_1_filtered, aes(x = value, y = variable, fill = "Untuned"), alpha = 0.5, scale = 1.2) +
  geom_density_ridges(data = data_2_filtered, aes(x = value, y = variable, fill = "Tuned"), alpha = 0.5, scale = 1.2) +
  scale_fill_manual(values = custom_colors) +
  labs(
    title = "Top 10 Side Effects: Performance After Tuning (Approved)",
    x = "LR Model Performance",
    y = "Side Effect"
  ) +
  theme_minimal(base_size = 15) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    axis.text.y = element_text(size = 12, margin = margin(r = 10)),  # Increased spacing
    plot.title = element_text(face = "bold", size = 12, hjust = 0),
    axis.title = element_text(face = "bold", size = 12)  # Bold axis titles
  )


```

